version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.6-node-browsers
        environment:
          GO111MODULE: "on"
    working_directory: ~/desktop
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run: 
          name: yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: lint with eslint
          command: yarn lint
      - run: 
          name: unit tests
          command: yarn test
      - run:
          name: publish to codecov
          command: yarn codecov
      - run:
          name: install qri backend & temp_registry_server
          command: go get github.com/qri-io/qri@HEAD github.com/qri-io/temp_registry_server
      - run:
          name: create artifacts path
          command: mkdir /home/circleci/e2e_artifacts
      - run:
          name: test e2e
          command: yarn test-e2e
          environment:
            HEADLESS_CHROME: 'true'
            E2E_ARTIFACTS_PATH: '/home/circleci/e2e_artifacts'
      - store_artifacts:
          path: ~/e2e_artifacts
          prefix: screenshots
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
